// Generated by CoffeeScript 1.4.0
var Home;

Home = (function() {

  function Home() {
    $("#main").html("<h1>This is home</h1>");
  }

  Home.prototype.index = function() {
    return $("#main").append("<p>This is the Index behavior of this action.</p>");
  };

  Home.prototype.multiply = function(a, b) {
    return $("#main").append("<p>The answer is " + (a * b) + ".</p>");
  };

  return Home;

})();
