// Generated by CoffeeScript 1.4.0
(function() {
  var Home;

  Home = (function() {

    function Home() {
      $(document).html("<h1>This is home</h1>");
    }

    Home.prototype.multiply = function(a, b) {
      return $(document).append("The answer is " + (a * b) + ".");
    };

    return Home;

  })();

}).call(this);
