// Generated by CoffeeScript 1.4.0
(function() {

  (function($, window) {
    var params, view, _import, _loadedModules;
    _loadedModules = new Array();
    /*
    	@exports _import as import
    */

    _import = function(name, options) {
      var defaults;
      defaults = {
        version: "",
        baseUrl: void 0,
        callback: void 0
      };
      if (typeof options === "function") {
        options = {
          callback: options
        };
      }
      options = $.extend(defaults, options);
      if (this.exists(name)) {
        return;
      }
      _loadedModules.push(name);
      $.holdReady(true);
      return $.getScript("" + baseUrl + name + version + ".js", function() {
        $.holdReady(false);
        if (options.callback) {
          return options.callback();
        }
      });
    };
    view = "home";
    params = {
      a: 1,
      b: 2
    };
    _import(view, function() {});
    return window["import"] = _import;
  })(jQuery, window);

}).call(this);
