// Generated by CoffeeScript 1.4.0

(function($, window) {
  var action, method, params;
  window.imports = (function() {
    var _loadedScripts;
    _loadedScripts = {};
    return function(name, options) {
      var defaults;
      defaults = {
        version: "",
        baseUrl: "js/",
        callback: void 0
      };
      if (typeof options === "function") {
        options = {
          callback: options
        };
      }
      options = $.extend(defaults, options);
      if (_loadedScripts[name]) {
        if (options.callback) {
          options.callback();
        }
        return;
      }
      _loadedScripts[name] = true;
      $.holdReady(true);
      return $.ajax({
        url: "" + options.baseUrl + name + ".js",
        dataType: "script",
        success: function() {
          $.holdReady(false);
          if (options.callback) {
            return options.callback();
          }
        },
        error: function() {
          return console.error("Problem loading script.");
        }
      });
    };
  })();
  params = location.hash.split("/");
  if (params.shift() !== "#!") {
    return;
  }
  action = params.shift() || "Home";
  method = params.shift() || "index";
  window.imports(action);
  return $(document).ready(function() {
    var obj;
    if (typeof window[action] === "function") {
      obj = new window[action];
      if (typeof obj[method] === "function") {
        return obj[method].apply(window, params);
      }
    } else {
      return console.error("Probably caps happened.");
    }
  });
})(jQuery, window);
